# For all pull requests made to master, next, dev branches, this workflow will:
# - install all dependencies
# - run all tests for the 'use-shopping-cart' workspace with pnpm

name: Tests

on:
  pull_request:
    branches: [master, next, dev]

jobs:
  test-package:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: ['18', '20', '22']
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ${{ matrix.node_version }}
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
          cache: pnpm

      # Install dependencies
      - run: pnpm install --frozen-lockfile
      # Run integration and unit tests
      - run: pnpm --filter use-shopping-cart run test
      # Run TypeScript type definition tests
      - run: pnpm --filter use-shopping-cart run test:types

  build-package:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Install dependencies
      - run: pnpm install --frozen-lockfile
      # Build package
      - run: pnpm --filter use-shopping-cart run build

  lint-package:
    continue-on-error: true
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Install dependencies
      - run: pnpm install --frozen-lockfile
      # Lint soure code
      - run: pnpm --filter use-shopping-cart run lint
